### STAGE 1: Build ###
FROM node:18-alpine3.15

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./

# ## Install python dependency (not by default in alpine version)
RUN apk add --update python3 make g++ \
    && rm -rf /var/cache/apk/*

RUN yarn

COPY . .

# Application metadata
CMD npx nx run main-app:serve --host 0.0.0.0 