version: '3.9'
services:
   mocking:
      container_name: mock
      image: securestacksolutions/wiremock
      ports:
         - '8080'
      volumes:
         - ./src/app/libs/mocks:/mocks
   main-app:
      container_name: app
      build:
         context: ../../
         dockerfile: ./apps/main-app/dockerfiles/Dockerfile.dev
      env_file:
         - ../../.env
      ports:
         - 8201:4200
      volumes:
         - '/app/node_modules'
         - '../../:/app'
      depends_on:
         - mocking
